### ISSUE TITLE
怎么获取数据呢

### ISSUE THREAD

**Issue by synchronizedCoder** [minh8023/ionic-citypicker#1]
请问下，如何获取选中后的数据呢？使用angular和ionic的时候，如何绑定所选择的地区数据？

**Comment by boolqiu** [comment]
在同一个控制器中如何复用？

**Comment by xudao520** [comment]
![image](https://cloud.githubusercontent.com/assets/12093709/11175769/dbe3ac0a-8c70-11e5-9b42-0ee8d1d75c96.png)指令中为什么会有几个scope，这样直接导致编译不通过

**Comment by xudao520** [comment]
@minh8023 好像指令中直接报错了哦

**Comment by minh8023** [comment]
@synchronizedCoder citydata 就是
```html
<ionic-city-picker citydata="vm.data"  button-clicked="vm.cb()" ></ionic-city-picker>
```

**Comment by minh8023** [comment]
@xudao520 嗯，上面那个scope是多余的。不过用于最新版本的ionic上面没有报错。你的报错提示是啥？

**Comment by minh8023** [comment]
@boolqiu 没懂你意思，放两个ionic-city-picker？ 只要citydata绑定不重复就可以。

**Comment by xudao520** [comment]
@minh8023 对我这边也去掉了，安卓编译可以正常，没去掉就不行

**Comment by minh8023** [comment]
@xudao520 嗯，你是对的，我只测过iOS下面。安卓没跑过。😄

**Comment by xudao520** [comment]
@minh8023 你这边好像数据结构都限定死了，两层的我没试估计不行

**Comment by minh8023** [comment]
数据我拿的淘宝的。。。然后就按它那结构写了。。。两层的改改也可以的

**Comment by xudao520** [comment]
是的，数据有点大，300多k我打算改了用接口加本地缓存的形式可能要好点
