### ISSUE TITLE
onScrollComplete 在 jsScrolling = false 时无效

### ISSUE THREAD

**Issue by sourbell** [minh8023/ionic-citypicker#4]
当设置
`$ionicConfigProvider.scrolling.jsScrolling(false);`
时，滚动事件没有调用 getValue() 方法。
我去掉这一句就正常了，不知道什么原因。

**Comment by sourbell** [comment]
解决了。 `<ion-scroll-minh>` 增加 `overflow-scroll=false` 即可。

**Comment by truebug** [comment]
赞一个，该方法解决了我在安卓下无法滚动选在到每列最后三行的问题。找rootcause找死，最后明白了原来是安卓下为了性能优化而设置了jsScrolling=false导致的...

**Comment by zwj47** [comment]
这bug作者貌似没发现。。

**Comment by Tian-Hun** [comment]
能说说具体的解决方法吗

**Comment by minh8023** [comment]
当初手上木有安卓机器，后来也转向react native了。

**Comment by aberror** [comment]
为什么转RN了？

**Comment by aberror** [comment]
@minh8023 后来怎么转react native了？
