### ISSUE TITLE
在手机上on-scroll-complete这个事件有时不会触发

### ISSUE THREAD

**Issue by ivanwonder** [minh8023/ionic-citypicker#6]
我看了一下，在手机上这个事件不可靠，经常省市区停在两个值中间，不知道你在手机上测试结果咋样。[bug: on-scroll-complete not reliably fired](https://github.com/driftyco/ionic/issues/3450)

**Comment by justgohead** [comment]
试试这个:
template:
<ion-scroll-minh on-release="vm.onRelease('province')" 
service:
vm.onRelease = function (name) {
                    switch (name) {
                        case 'province':
                            var Handle = vm.provinceHandle
                            break
                        case 'city':
                            Handle = vm.cityHandle
                            break
                    }
                    vm.runing = $timeout(function () {
                        var top = $ionicScrollDelegate.$getByHandle(Handle).getScrollPosition().top
                        $ionicScrollDelegate.$getByHandle(Handle).scrollTo(0, top + 0.1, true)
                    }, 10)
                }

**Comment by ivanwonder** [comment]
@justgohead 看了一下你的思路，是在手指离开屏幕的时候，延时触发插件的数据更新操作吧，这样我连续滑动的时候突然更新界面，体验不太好吧。我觉得使用onscroll事件实时监听滚动比较好，每次触发onscroll事件时，关闭上一个runing定时器，同时新建一个running的定时器，时间设置只要比ionic触发onscroll的间隔稍长即可。

**Comment by gavinmygit** [comment]
@ivanwonder ,具体怎么解决呢，就是移动端，省市区vm.getValue 方法有时候不走的问题，还望大神帮忙，感谢

**Comment by gavinmygit** [comment]
html:
<ion-scroll-minh on-scroll = "vm.onScrolling('province')" ..>

ionic-citypicker:
 vm.onScrolling = function (name) {
            switch (name) {
                case 'province':
                    var Handle = vm.provinceHandle;
                    break;
                case 'city':
                    Handle = vm.cityHandle;
                    break;
            }
            $timeout.cancel(vm.runing);
            vm.runing = $timeout(function () {
                var top = $ionicScrollDelegate.$getByHandle(Handle).getScrollPosition().top;
                $ionicScrollDelegate.$getByHandle(Handle).scrollTo(0, top+0.01, true)
            }, 36)
        };
亲测，可用

**Comment by HHL0406** [comment]
要怎样使这个插件既支持Android又支持IOS？

**Comment by ivanwonder** [comment]
@gavinmygit @HHL0406 反正onscroll比较靠谱，然后通过定时器去检查是不是在滑动，onscroll好像是默认500ms执行一次，如果500ms后没有执行，那就是没有滚动了，你在scrollTo就行了。

**Comment by HHL0406** [comment]
@ivanwonder 知道怎样修改才能让它同时支持安卓和IOS系统吗，麻烦帮帮忙
